{{- if .Values.redis.enabled }}
{{- if and .Values.redis.auth.enabled (not .Values.redis.auth.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "earthgazer.fullname" . }}-redis
  labels:
    {{- include "earthgazer.labels" . | nindent 4 }}
    app.kubernetes.io/component: redis
type: Opaque
data:
  redis-password: {{ .Values.redis.auth.password | b64enc | quote }}
{{- end }}
{{- end }}
