{{- if .Values.redis.enabled }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "earthgazer.fullname" . }}-redis
  labels:
    {{- include "earthgazer.labels" . | nindent 4 }}
    app.kubernetes.io/component: redis
spec:
  serviceName: {{ include "earthgazer.fullname" . }}-redis
  replicas: 1
  selector:
    matchLabels:
      {{- include "earthgazer.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: redis
  template:
    metadata:
      labels:
        {{- include "earthgazer.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: redis
    spec:
      containers:
      - name: redis
        image: "{{ .Values.redis.image.registry }}/{{ .Values.redis.image.repository }}:{{ .Values.redis.image.tag }}"
        imagePullPolicy: {{ .Values.redis.image.pullPolicy }}
        ports:
        - name: redis
          containerPort: 6379
          protocol: TCP
        {{- if .Values.redis.auth.enabled }}
        command:
        - redis-server
        - --requirepass
        - $(REDIS_PASSWORD)
        - --appendonly
        - "yes"
        env:
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ include "earthgazer.fullname" . }}-redis
              key: redis-password
        {{- else }}
        command:
        - redis-server
        - --appendonly
        - "yes"
        {{- end }}
        volumeMounts:
        - name: data
          mountPath: /data
        {{- if .Values.redis.master.resources }}
        resources:
          {{- toYaml .Values.redis.master.resources | nindent 10 }}
        {{- end }}
        livenessProbe:
          exec:
            command:
            - sh
            - -c
            {{- if .Values.redis.auth.enabled }}
            - redis-cli -a $REDIS_PASSWORD ping | grep PONG
            {{- else }}
            - redis-cli ping | grep PONG
            {{- end }}
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 5
        readinessProbe:
          exec:
            command:
            - sh
            - -c
            {{- if .Values.redis.auth.enabled }}
            - redis-cli -a $REDIS_PASSWORD ping | grep PONG
            {{- else }}
            - redis-cli ping | grep PONG
            {{- end }}
          initialDelaySeconds: 5
          periodSeconds: 10
          timeoutSeconds: 1
          failureThreshold: 5
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes:
      - ReadWriteOnce
      {{- if .Values.redis.master.persistence.storageClass }}
      storageClassName: {{ .Values.redis.master.persistence.storageClass | quote }}
      {{- end }}
      resources:
        requests:
          storage: {{ .Values.redis.master.persistence.size | quote }}
{{- end }}
