{{- if .Values.postgresql.enabled }}
{{- if not .Values.postgresql.auth.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "earthgazer.fullname" . }}-postgresql
  labels:
    {{- include "earthgazer.labels" . | nindent 4 }}
    app.kubernetes.io/component: database
type: Opaque
data:
  postgres-password: {{ .Values.postgresql.auth.password | b64enc | quote }}
{{- end }}
{{- end }}
