{{- if and .Values.flower.enabled .Values.flower.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "earthgazer.fullname" . }}-flower
  labels:
    {{- include "earthgazer.labels" . | nindent 4 }}
    component: flower
  {{- with .Values.flower.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.flower.ingress.className }}
  ingressClassName: {{ .Values.flower.ingress.className }}
  {{- end }}
  {{- if .Values.flower.ingress.tls }}
  tls:
    {{- range .Values.flower.ingress.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
  rules:
    {{- range .Values.flower.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ .path }}
            pathType: {{ .pathType }}
            backend:
              service:
                name: {{ include "earthgazer.fullname" $ }}-flower
                port:
                  number: {{ $.Values.flower.service.port }}
          {{- end }}
    {{- end }}
{{- end }}
