{{- if .Values.flower.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "earthgazer.fullname" . }}-flower
  labels:
    {{- include "earthgazer.labels" . | nindent 4 }}
    component: flower
spec:
  type: {{ .Values.flower.service.type }}
  ports:
    - port: {{ .Values.flower.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "earthgazer.selectorLabels" . | nindent 4 }}
    component: flower
{{- end }}
