{{- if not .Values.gcloud.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "earthgazer.fullname" . }}-gcloud
  labels:
    {{- include "earthgazer.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.gcloud.serviceAccount }}
  service-account.json: {{ .Values.gcloud.serviceAccount }}
  {{- else }}
  service-account.json: ""
  {{- end }}
{{- end }}
---
{{- if not .Values.flower.auth.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "earthgazer.fullname" . }}-flower
  labels:
    {{- include "earthgazer.labels" . | nindent 4 }}
type: Opaque
stringData:
  username: {{ .Values.flower.auth.username | quote }}
  password: {{ .Values.flower.auth.password | quote }}
{{- end }}
