apiVersion: v2
name: earthgazer
description: A Helm chart for EarthGazer - Satellite image processing and analysis platform
type: application
version: 1.0.0
appVersion: "1.0.0"

keywords:
  - satellite
  - geospatial
  - celery
  - sentinel
  - landsat
  - ndvi
  - remote-sensing

maintainers:
  - name: Alvaro Bravo
    email: alvaroubravo@mxdata.dev

annotations:
  category: BigData
  licenses: Apache-2.0
